apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-cloud-good
  name: java-cloud-good
  namespace: prod
spec:
  ports:
  - nodePort: 30206
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-cloud-good
  type: NodePort
