apiVersion: v1
kind: Service
metadata:
  labels:
    app: openresty-healthcheck
  name: openresty-healthcheck
  namespace: prod
spec:
  ports:
  - nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openresty-healthcheck
  type: NodePort
