apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      version: 1.14.2
  template:
    metadata:
      labels:
        app: nginx
        version: 1.14.2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - name: http
          containerPort: 80
