apiVersion: v1
kind: Service
metadata: 
  name: nginx-deploy
  namespace: default
spec:
  selector:
    app: nginx
    version: 1.14.2
  clusterIP: 10.99.99.99
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
